blank_issues_enabled: true
contact_links:
  - name: ğŸ‘¨â€ğŸ« ArduinoJson Assistant
    url: https://arduinojson.org/v7/assistant/
    about: An online tool that computes memory requirements and generates scaffolding code for your project.
  - name: ğŸ‘¨â€âš•ï¸ ArduinoJson Troubleshooter
    url: https://arduinojson.org/v7/troubleshooter/
    about: An online tool that helps you diagnose the most common issues with ArduinoJson.
